Output ./assets/pwgo-selecting.gif

Set WindowBar Colorful
Set WindowBarSize 70
Set Theme "nord"
Set Shell "bash"
Set FontSize 20
Set Width 1400
Set Height 1000

Type "pwgo --project firefox"
Enter
Sleep 1s
Type "/"
Sleep 1s
Type "un-mark"
Sleep 1s
Enter
Sleep 1s
Space
Sleep 1s
Type "j"
Sleep 1s
Space
Sleep 1s
Type "Shift+H"
Sleep 3s
Space
Sleep 2s
Enter
Sleep 1s

Hide

Ctrl+c
Type "clear"
Enter

Show

